"""empty message

Revision ID: 1e4424ce1886
Revises: 3d645ec3e069
Create Date: 2023-03-25 20:37:47.728336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4424ce1886'
down_revision = '3d645ec3e069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ipv4address', sa.String(length=12), nullable=False),
    sa.Column('ipv6address', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'unknown'), server_default='unknown', nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipv4address'),
    sa.UniqueConstraint('ipv6address'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
