"""empty message

Revision ID: 3150aa609e11
Revises: 878df8a46241
Create Date: 2023-03-25 20:40:22.128152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3150aa609e11'
down_revision = '878df8a46241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=100), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
