"""empty message

Revision ID: 371b215fe3be
Revises: 3150aa609e11
Create Date: 2023-03-25 20:40:59.480495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371b215fe3be'
down_revision = '3150aa609e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
