"""empty message

Revision ID: 392a6e1ec0a2
Revises: 9d5f4d747504
Create Date: 2023-03-25 17:01:12.983994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392a6e1ec0a2'
down_revision = '9d5f4d747504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'suspended', 'stopped', 'deleted', 'active', 'unknown'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'suspended', 'stopped', 'deleted', 'active', 'unknown'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
