"""empty message

Revision ID: 3d645ec3e069
Revises: 392a6e1ec0a2
Create Date: 2023-03-25 17:08:30.355153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d645ec3e069'
down_revision = '392a6e1ec0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.Enum('Thika'), server_default='Thika', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
