"""added clients and plans tables

Revision ID: 64e233431e5b
Revises: 
Create Date: 2023-03-22 20:11:16.203858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e233431e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('ostemplate', sa.String(length=100), nullable=True),
    sa.Column('bwlimit', sa.Integer(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('rootfs', sa.String(length=100), nullable=True),
    sa.Column('storage', sa.String(length=100), nullable=True),
    sa.Column('ostype', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderdate', sa.DateTime(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('node', sa.String(length=100), nullable=True),
    sa.Column('vmid', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('pending', 'stopped', 'deleted', 'active'), server_default='pending', nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vmid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###
