"""empty message

Revision ID: 9d5f4d747504
Revises: 35b31f17072f
Create Date: 2023-03-23 20:14:38.118248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5f4d747504'
down_revision = '35b31f17072f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('expirydate',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('expirydate',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
