name: Build and Deploy Docker Image for ISP Portal

env:
  APP_VERSION: 1.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ispportal:$APP_VERSION

          